### ISSUE TITLE
add a column frame

### ISSUE THREAD

**Issue by samcarter8** [louisstuart96/beamer-benchmark#1]
Interesting project! It seems like you already have all the critical elements.

Maybe a small addition: a frame to test the behaviour of columns might be useful.

```
\begin{frame}
\frametitle{Testing columns}
	\begin{columns}[onlytextwidth,t]
		\begin{column}{.3\textwidth}
			\begin{itemize}
				\item test
			\end{itemize}
			\rule{\linewidth}{2pt}
		\end{column}
		\begin{column}{.3\textwidth}
			text
			\rule{\linewidth}{2pt}
		\end{column}	
		\begin{column}{.3\textwidth}
			\begin{block}{title}
				text
			\end{block}
			\rule{\linewidth}{2pt}
		\end{column}			
	\end{columns}
\end{frame}
```

**Comment by louisstuart96** [comment]
Added in https://github.com/louisstuart96/beamer-benchmark/commit/0091f8e013b036e543abc6557b6d0531934bc604 . 
Note that the vertical alignment of `\vtop` boxes involve `\special` items brought by color commands.
